/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiSendVerificationEmailRouteRouteImport } from './routes/api/send-verification-email/route'
import { Route as ApiSendPasswordResetEmailRouteRouteImport } from './routes/api/send-password-reset-email/route'
import { Route as ApiSendEmailChangeRouteRouteImport } from './routes/api/send-email-change/route'
import { Route as ApiSendDeleteAccountVerificationEmailRouteRouteImport } from './routes/api/send-delete-account-verification-email/route'
import { Route as ProtectedSessionsIndexRouteImport } from './routes/_protected/sessions/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedDangerIndexRouteImport } from './routes/_protected/danger/index'
import { Route as ProtectedAccountsIndexRouteImport } from './routes/_protected/accounts/index'
import { Route as AuthLayoutSignUpIndexRouteImport } from './routes/_authLayout/sign-up/index'
import { Route as AuthLayoutResetPasswordIndexRouteImport } from './routes/_authLayout/reset-password/index'
import { Route as AuthLayoutLoginIndexRouteImport } from './routes/_authLayout/login/index'
import { Route as AuthLayoutForgotPasswordIndexRouteImport } from './routes/_authLayout/forgot-password/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiSendVerificationEmailRouteRoute =
  ApiSendVerificationEmailRouteRouteImport.update({
    id: '/api/send-verification-email',
    path: '/api/send-verification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSendPasswordResetEmailRouteRoute =
  ApiSendPasswordResetEmailRouteRouteImport.update({
    id: '/api/send-password-reset-email',
    path: '/api/send-password-reset-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSendEmailChangeRouteRoute = ApiSendEmailChangeRouteRouteImport.update({
  id: '/api/send-email-change',
  path: '/api/send-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendDeleteAccountVerificationEmailRouteRoute =
  ApiSendDeleteAccountVerificationEmailRouteRouteImport.update({
    id: '/api/send-delete-account-verification-email',
    path: '/api/send-delete-account-verification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSessionsIndexRoute = ProtectedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDangerIndexRoute = ProtectedDangerIndexRouteImport.update({
  id: '/danger/',
  path: '/danger/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAccountsIndexRoute = ProtectedAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLayoutSignUpIndexRoute = AuthLayoutSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutResetPasswordIndexRoute =
  AuthLayoutResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayoutLoginIndexRoute = AuthLayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutForgotPasswordIndexRoute =
  AuthLayoutForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/send-delete-account-verification-email': typeof ApiSendDeleteAccountVerificationEmailRouteRoute
  '/api/send-email-change': typeof ApiSendEmailChangeRouteRoute
  '/api/send-password-reset-email': typeof ApiSendPasswordResetEmailRouteRoute
  '/api/send-verification-email': typeof ApiSendVerificationEmailRouteRoute
  '/': typeof ProtectedIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordIndexRoute
  '/login': typeof AuthLayoutLoginIndexRoute
  '/reset-password': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up': typeof AuthLayoutSignUpIndexRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/danger': typeof ProtectedDangerIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/sessions': typeof ProtectedSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/api/send-delete-account-verification-email': typeof ApiSendDeleteAccountVerificationEmailRouteRoute
  '/api/send-email-change': typeof ApiSendEmailChangeRouteRoute
  '/api/send-password-reset-email': typeof ApiSendPasswordResetEmailRouteRoute
  '/api/send-verification-email': typeof ApiSendVerificationEmailRouteRoute
  '/': typeof ProtectedIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordIndexRoute
  '/login': typeof AuthLayoutLoginIndexRoute
  '/reset-password': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up': typeof AuthLayoutSignUpIndexRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/danger': typeof ProtectedDangerIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/sessions': typeof ProtectedSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/api/send-delete-account-verification-email': typeof ApiSendDeleteAccountVerificationEmailRouteRoute
  '/api/send-email-change': typeof ApiSendEmailChangeRouteRoute
  '/api/send-password-reset-email': typeof ApiSendPasswordResetEmailRouteRoute
  '/api/send-verification-email': typeof ApiSendVerificationEmailRouteRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authLayout/forgot-password/': typeof AuthLayoutForgotPasswordIndexRoute
  '/_authLayout/login/': typeof AuthLayoutLoginIndexRoute
  '/_authLayout/reset-password/': typeof AuthLayoutResetPasswordIndexRoute
  '/_authLayout/sign-up/': typeof AuthLayoutSignUpIndexRoute
  '/_protected/accounts/': typeof ProtectedAccountsIndexRoute
  '/_protected/danger/': typeof ProtectedDangerIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/sessions/': typeof ProtectedSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/send-delete-account-verification-email'
    | '/api/send-email-change'
    | '/api/send-password-reset-email'
    | '/api/send-verification-email'
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/accounts'
    | '/danger'
    | '/profile'
    | '/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/send-delete-account-verification-email'
    | '/api/send-email-change'
    | '/api/send-password-reset-email'
    | '/api/send-verification-email'
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/accounts'
    | '/danger'
    | '/profile'
    | '/sessions'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_protected'
    | '/api/send-delete-account-verification-email'
    | '/api/send-email-change'
    | '/api/send-password-reset-email'
    | '/api/send-verification-email'
    | '/_protected/'
    | '/privacy/'
    | '/terms/'
    | '/api/auth/$'
    | '/_authLayout/forgot-password/'
    | '/_authLayout/login/'
    | '/_authLayout/reset-password/'
    | '/_authLayout/sign-up/'
    | '/_protected/accounts/'
    | '/_protected/danger/'
    | '/_protected/profile/'
    | '/_protected/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiSendDeleteAccountVerificationEmailRouteRoute: typeof ApiSendDeleteAccountVerificationEmailRouteRoute
  ApiSendEmailChangeRouteRoute: typeof ApiSendEmailChangeRouteRoute
  ApiSendPasswordResetEmailRouteRoute: typeof ApiSendPasswordResetEmailRouteRoute
  ApiSendVerificationEmailRouteRoute: typeof ApiSendVerificationEmailRouteRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/send-verification-email': {
      id: '/api/send-verification-email'
      path: '/api/send-verification-email'
      fullPath: '/api/send-verification-email'
      preLoaderRoute: typeof ApiSendVerificationEmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-password-reset-email': {
      id: '/api/send-password-reset-email'
      path: '/api/send-password-reset-email'
      fullPath: '/api/send-password-reset-email'
      preLoaderRoute: typeof ApiSendPasswordResetEmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email-change': {
      id: '/api/send-email-change'
      path: '/api/send-email-change'
      fullPath: '/api/send-email-change'
      preLoaderRoute: typeof ApiSendEmailChangeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-delete-account-verification-email': {
      id: '/api/send-delete-account-verification-email'
      path: '/api/send-delete-account-verification-email'
      fullPath: '/api/send-delete-account-verification-email'
      preLoaderRoute: typeof ApiSendDeleteAccountVerificationEmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/sessions/': {
      id: '/_protected/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof ProtectedSessionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/danger/': {
      id: '/_protected/danger/'
      path: '/danger'
      fullPath: '/danger'
      preLoaderRoute: typeof ProtectedDangerIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/accounts/': {
      id: '/_protected/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_authLayout/sign-up/': {
      id: '/_authLayout/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthLayoutSignUpIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/reset-password/': {
      id: '/_authLayout/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthLayoutResetPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/login/': {
      id: '/_authLayout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/forgot-password/': {
      id: '/_authLayout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutForgotPasswordIndexRoute: typeof AuthLayoutForgotPasswordIndexRoute
  AuthLayoutLoginIndexRoute: typeof AuthLayoutLoginIndexRoute
  AuthLayoutResetPasswordIndexRoute: typeof AuthLayoutResetPasswordIndexRoute
  AuthLayoutSignUpIndexRoute: typeof AuthLayoutSignUpIndexRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutForgotPasswordIndexRoute: AuthLayoutForgotPasswordIndexRoute,
  AuthLayoutLoginIndexRoute: AuthLayoutLoginIndexRoute,
  AuthLayoutResetPasswordIndexRoute: AuthLayoutResetPasswordIndexRoute,
  AuthLayoutSignUpIndexRoute: AuthLayoutSignUpIndexRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedAccountsIndexRoute: typeof ProtectedAccountsIndexRoute
  ProtectedDangerIndexRoute: typeof ProtectedDangerIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedSessionsIndexRoute: typeof ProtectedSessionsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedAccountsIndexRoute: ProtectedAccountsIndexRoute,
  ProtectedDangerIndexRoute: ProtectedDangerIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedSessionsIndexRoute: ProtectedSessionsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiSendDeleteAccountVerificationEmailRouteRoute:
    ApiSendDeleteAccountVerificationEmailRouteRoute,
  ApiSendEmailChangeRouteRoute: ApiSendEmailChangeRouteRoute,
  ApiSendPasswordResetEmailRouteRoute: ApiSendPasswordResetEmailRouteRoute,
  ApiSendVerificationEmailRouteRoute: ApiSendVerificationEmailRouteRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
